### ISSUE TITLE
RPG rockets multiplies

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#249] opened 2016-06-08 17:16 UTC
RPG rockets gets multiplied every time you use.

**Comment by kadaradam** [comment] 2016-06-08 17:24
You should not have a server if you can't manage it...

**Comment by XFlawless1** [comment] 2016-06-08 17:27
RPG rockets is a real bug isn't it and fuel can
Last update got it bad
Lift was wrongly posted and yes if u do /hud and /hud agian then only the food bar works.

**Comment by Southclaw** [comment] 2016-06-08 17:42
It's a good idea to use the releases rather than latest commits on a public server. Topic branches are merged into master once they are feature-complete, this does not mean they are bug free and the master branch still does not signify stability! This is why the last release is 16 commits behind master.

**Closed** 2016-06-08 18:08 UTC
Labels: bug

**Comment by Southclaw** [comment] 2016-06-08 19:39
Cannot reproduce fuel can issue on 3926b7b50a74c98b4164cd0d608558d5ff15f43c:

![https://dl.dropboxusercontent.com/u/45512231/ShareX/2016-06-08_20-38-48.gif](https://dl.dropboxusercontent.com/u/45512231/ShareX/2016-06-08_20-38-48.gif)

Food bar also works fine on that commit.

**Comment by XFlawless1** [comment] 2016-06-09 07:09
Nope its still that @Southclaw 
I don't know why that happens.
