### ISSUE TITLE
[GetItemArrayDataAtCell] ERROR: Cell 0 exceeds item type (70) max of 0.

### ISSUE THREAD

**Issue by trojan-sas** [Southclaw/ScavengeSurvive#265] opened 2016-06-28 18:37 UTC
first of all no words can describe how im admired by ur gamemode.. however theirs some bugs  that was a pain in ass i really apreatiate if u can find out how we can fix this :
 its related to https://github.com/Southclaw/ScavengeSurvive/issues/263 when players try to synced  a phone to remote TNT,IED its gives error code:
 [20:41:40] [GetItemArrayDataAtCell] ERROR: Cell 0 exceeds item type (70) max of 0.
[20:41:40] [GetItemArrayDataAtCell] ERROR: Cell 0 exceeds item type (70) max of 0.
[20:41:40] [GetItemArrayDataAtCell] ERROR: Cell 0 exceeds item type (70) max of 0.
[20:41:40] [GetItemArrayDataAtCell] ERROR: Cell 0 exceeds item type (70) max of 0.
[20:41:40] [GetItemArrayDataAtCell] ERROR: Cell 0 exceeds item type (70) max of 0.
[20:41:41] [GetItemArrayDataAtCell] ERROR: Cell 0 exceeds item type (70) max of 0.

**Comment by kadaradam** [comment] 2016-06-28 18:48
Set the bomb item max array data to 1, and the problem is fixed.

**Comment by Southclaw** [comment] 2016-06-28 19:41
Will be fixed when explosive-update is finished and merged to master.

In the mean time, kadaradam has the correct fix. I will add an itemtype to these error messages so you can report the items affected.

**Comment by trojan-sas** [comment] 2016-06-29 20:00
fixed thanks @kadaradam @Southclaw

**Closed** 2016-06-29 20:00 UTC
