### ISSUE TITLE
Settings problem

### ISSUE THREAD

**Issue by SkullFire** [Southclaw/ScavengeSurvive#164] opened 2015-11-28 15:29 UTC
Server was not reading the settings.ini.
The server only reads the file when it is non-existent,after the server is turned off it can no longer read the settings.ini the settings return pro standard script or variable = 0.

**Comment by Southclaw** [comment] 2015-11-28 16:40
Windows or Linux? Which code revision? Any errors on the console or on compilation? Does the file have read/write permissions? What's in the file after it's created?

**Comment by SkullFire** [comment] 2015-11-28 19:16
One question. This function uses FileManager?

**Comment by Southclaw** [comment] 2015-11-28 19:45
No, it uses SimpleINI, which uses the basic file functions.

**Comment by SkullFire** [comment] 2015-11-28 21:22
Btw I fixed it, thanks for help.
The file settings.ini gets messe when its created, i had to tidy it

**Comment by Southclaw** [comment] 2015-11-29 00:31
Can you provide details? How did you fix it? Can you submit a pull request so other users don't experience the same problem?

**Comment by SkullFire** [comment] 2015-11-30 13:26
Damn,for a while I thought it was fixed, but the file was messed again.

It is getting everything together and I think that's why the server is not reading the settings folder
exemple:
 3.000000player/combat-log-window =30player/login-freeze-time = .. etc etc

**Comment by Southclaw** [comment] 2015-11-30 16:26
I'll ask again: Windows or Linux? Which code revision? Any errors on the console or on compilation? Does the file have read/write permissions? What's in the file after it's created?

Looks like line endings. Probably an issue for [SimpleINI](https://github.com/Southclaw/SimpleINI) since that library handles the reading/writing. This library will always write Unix line endings (LF).

**Comment by SkullFire** [comment] 2015-11-30 18:04
I had this server in both OS.
No errors in my pc(windows), but the problem keepsl
Socker errors in console, but rthe ser keeps online

**Comment by SkullFire** [comment] 2015-12-02 20:51
loading configs:
[15:48:33] [LOAD] server/motd: test
[15:48:33] [LOAD] server/website: test
[15:48:33] ERROR: key 'server/rules/0' not found.
[15:48:33] ERROR: key 'server/staff/0' not found.
[15:48:33] [LOAD] server/max-uptime: 0
[15:48:33] [LOAD] player/allow-pause-map: 0
[15:48:33] [LOAD] player/interior-entry: 0
[15:48:33] [LOAD] player/player-animations: 0
[15:48:33] [LOAD] player/vehicle-surfing: 0
[15:48:33] [LOAD] player/nametag-distance: 0.000000
[15:48:33] [LOAD] player/combat-log-window: 0
[15:48:33] [LOAD] player/login-freeze-time: 0
[15:48:33] [LOAD] player/max-tab-out-time: 0
[15:48:33] [LOAD] player/ping-limit: 0

**Comment by Southclaw** [comment] 2015-12-04 11:29
Try the new SimpleINI version now, I couldn't reproduce your problem but I fixed some small things and replaced the strcpy macro with a function.

**Comment by SkullFire** [comment] 2015-12-04 21:39
i think you has forgotten to update on github

**Comment by Southclaw** [comment] 2015-12-05 10:04
I committed yesterday but Git doesn't seem to want to push that repo for some reason...

**Closed** 2016-01-19 12:36 UTC
